apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netai-model-pvc
  namespace: netai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netai-data-pvc
  namespace: netai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
